# Communicate Data Findings Project

## Part 1 - PISA Data

The data set is comprised of selected demographic, student and parent questionnaire responses, and quantitative scores produced from a variety of questionnaire booklets for China, Singapore, and United States of America.  The student questionnaire responses cover topics including school, learning resources, attitudes towards math and school, and student opinions of their teachers.  

<strong>Store data attributes into one CSV file called pisa2012_data.csv</strong>

- Download pisa 2012 data file
- Load pisa 2012 data into sqlite database table
- Load subset of pisa 2012 data into csv file
- Map pisa columns into readable columns names for selected attributes

In [1]:
import pandas as pd
import numpy as np
from pisa_data_load import load_pisa_database

### Download raw PISA CSV file
The PISA raw dataset can be downloaded from https://www.oecd.org/pisa/pisaproducts/database-cbapisa2012.htm

### Load raw PISA CSV file into sqlite database
There are about 500,000 records in the pisa20012.csv file. The code below was used to load the raw pisa CSV file into a new sqlite database table called pisa.  The raw pisa csv data file is in the data/pisa2012.zip file

In [8]:
# load the pisa 2012 data file into sqlite3 database table
file = 'pisa2012.csv'
load_pisa_database(file)

### Create new PISA CSV file with new column names
- Execute the sql query below in a sqlite terminal 
- Save the results to a new CSV file called pisa2012_data.csv

SELECT  CNT AS country,
	SUBNATIO AS sub_nation_code,
	STRATUM AS stratum,
	OECD ,
	NC AS natnl_center,
	SCHOOLID school_id,
	ST15Q01 AS mother_curr_job_status,
	ST19Q01 AS father_curr_job_status,
	ST35Q04 AS parents_believe_math_study,
	ST35Q05 AS parents_believe_math_career,
	ST35Q06 AS parents_like_math,
	HEDRES AS home_ed_resources,
	PARED AS highest_parent_education_yrs,
	ST04Q01 AS gender,
	ST08Q01 AS truancy_late,
	ST09Q01 AS truancy_skip_day,
	ST115Q01 AS truancy_skip_classes,
	ST11Q01 AS mother_at_home,
	ST11Q02 AS father_at_home,
	ST11Q03 AS brothers_at_home,
	ST11Q04 AS sisters_at_home,
	ST26Q01 AS owns_desk,
	ST26Q04 AS owns_computer,
	ST26Q06 AS possession_internet,
    ST29Q02 AS math_worthwhile_for_work, -- Instrumental Motivation - Worthwhile for Work
    ST29Q03 AS look_fwd_to_lessons, -- Math Interest - Look Forward to Lessons
    ST29Q04 AS enjoy_math, -- Math Interest - Enjoy Maths
    ST29Q05 AS worthwhile_career, -- Instrumental Motivation - Worthwhile for Career Chances
    ST29Q06 AS math_interested, -- Math Interest - Interested
    ST42Q02 AS not_good_math, -- Math Self-Concept - Not Good at Maths
    ST42Q04 AS gets_good_grades, -- Math Self-Concept- Get Good <Grades>
    ST42Q05 AS gets_nervous, -- Math Anxiety - Get Very Nervous
    ST42Q06 AS learn_quickly, -- Math Self-Concept - Learn Quickly
    ST42Q07 AS one_of_best_subjects, -- Math Self-Concept - One of Best Subjects
    ST42Q08 AS feel_helpless, -- Math Anxiety - Feel Helpless
    ST46Q01 AS homework_on_time, -- Math Work Ethic - Homework Completed in Time
    ST46Q02 AS homework_work_hard, -- Math Work Ethic - Work Hard on Homework
    ST46Q03 AS math_prepared_exams, -- Math Work Ethic - Prepared for Exams
    ST46Q04 AS math_study_quiz, -- Math Work Ethic - Study Hard for Quizzes
    ST46Q05 AS math_study_understand, -- Math Work Ethic - Study Until I Understand Everything
    ST46Q06 AS math_pay_attention, -- Math Work Ethic - Pay Attention in Classes
    ST46Q07 AS math_listen_in_class, -- Math Work Ethic - Listen in Classes
    ST46Q08 AS math_avoid_distraction, -- Math Work Ethic - Avoid Distractions When Studying
    ST46Q09 AS math_keep_work_organized, -- Math Work Ethic - Keep Work Organized
    ST48Q02 AS behaviour_math_sci_college_major, -- Math Intentions - Mathematics vs. Science Related Major in College
    ST48Q04 AS behaviour_max_math_sci_classes, -- Math Intentions - Take Max Number of Mathematics vs. Science Classes
    ST48Q05 AS behaviour_pursue_mathsci_career, -- Math Intentions - Pursuing a Career Mathematics vs. Science
    ST49Q01 AS behaviour_talk_math_friend, -- Math Behaviour - Talk about Maths with Friends
    ST49Q02 AS behaviour_help_friend_math, -- Math Behaviour - Help Friends with Maths
    ST49Q03 AS behaviour_extrac_activity, -- Math Behaviour - <Extracurricular> Activity
    ST49Q04 AS behaviour_partic_competition, -- Math Behaviour - Participate in Competitions
    ST49Q05 AS behaviour_study_2extra_hrs, -- Math Behaviour - Study More Than 2 Extra Hours a Day
    ST49Q06 AS behaviour_play_chess, -- Math Behaviour - Play Chess
    ST49Q07 AS behaviour_computer_programming, -- Math Behaviour - Computer programming
    ST49Q09 AS behaviour_math_club, -- Math Behaviour - Participate in Math Club
    ST55Q02 AS outof_school_lessons, -- Out of school lessons - <maths>
    ST57Q01 AS outof_school_study_time, -- Out-of-School Study Time - Homework
    ST57Q02 AS outof_school_study_guided_hw, -- Out-of-School Study Time - Guided Homework
    ST57Q03 AS outof_school_study_tutor, -- Out-of-School Study Time - Personal Tutor
    ST57Q04 AS outof_school_study_comm_co, -- Out-of-School Study Time - Commercial Company
    ST57Q05 AS outof_school_study_parent, -- Out-of-School Study Time - With Parent
    ST57Q06 AS outof_school_study_computer, -- Out-of-School Study Time - Computer
    ST62Q01 AS familiar_exp_function, -- Familiarity with Math Concepts - Exponential Function
    ST62Q02 AS familiar_divisor, -- Familiarity with Math Concepts - Divisor
    ST62Q03 AS familiar_quadratic, -- Familiarity with Math Concepts - Quadratic Function
    ST62Q06 AS familiar_linear_eq, -- Familiarity with Math Concepts - Linear Equation
    ST62Q07 AS familiar_vectors, -- Familiarity with Math Concepts - Vectors
    ST62Q08 AS familiar_complex_numb, -- Familiarity with Math Concepts - Complex Number
    ST62Q09 AS familiar_rational_numb, -- Familiarity with Math Concepts - Rational Number
    ST62Q10 AS familiar_radicals, -- Familiarity with Math Concepts - Radicals
    ST62Q12 AS familiar_polygon, -- Familiarity with Math Concepts - Polygon
    ST62Q15 AS familiar_congruent_fig, -- Familiarity with Math Concepts - Congruent Figure
    ST62Q16 AS familiar_cosine, -- Familiarity with Math Concepts - Cosine
    ST62Q17 AS familiar_arith_mean, -- Familiarity with Math Concepts - Arithmetic Mean
    ST62Q19 AS familiar_probability, -- Familiarity with Math Concepts - Probability
    ST87Q01 AS belonging_feel_outsider, -- Sense of Belonging - Feel Like Outsider
    ST87Q02 AS belonging_make_friends, -- Sense of Belonging - Make Friends Easily
    ST87Q03 AS belonging_at_sch, -- Sense of Belonging - Belong at School
    ST87Q04 AS belonging_feel_awkward_sch, -- Sense of Belonging - Feel Awkward at School
    ST87Q05 AS belonging_liked_byothers, -- Sense of Belonging - Liked by Other Students
    ST87Q06 AS belonging_feel_lonely_sch, -- Sense of Belonging - Feel Lonely at School
    ST87Q07 AS belonging_feel_happy_sch, -- Sense of Belonging - Feel Happy at School
    ST87Q08 AS belonging_ideal_atsch, -- Sense of Belonging - Things Are Ideal at School
    ST87Q09 AS belonging_satisfied_atsch, -- Sense of Belonging - Satisfied at School
    IC01Q01 AS athome_desktop_computer, -- At Home - Desktop Computer
    IC01Q04 AS athome_internet, -- At Home - Internet connection
    IC01Q07 AS athome_cellphone_internet, -- At Home - Cell phone with Internet
    IC01Q09 AS athome_printer, -- At Home - Printer
    IC02Q01 AS atsch_desktop_computer, -- At school - Desktop Computer
    IC02Q04 AS atsch_internet,  -- At school - Internet connection
    IC02Q05 AS atsch_printer,  -- At school - Printer
    ST29Q07 AS important_fut_study,  -- Instrumental Motivation - Important for Future Study
    ST29Q08 AS help_get_job,  -- Instrumental Motivation - Helps to Get a Job
    ST43Q01 AS succeed_with_effort,  -- Perceived Control - Can Succeed with Enough Effort
    ST43Q02 AS completely_upto_me,  -- Perceived Control - Doing Well is Completely Up to Me
    ST70Q02 AS no_of_math_classes_wk,  -- No of <class period> p/wk - <Maths>
    ST71Q01 AS no_of_all_classes_wk,  -- No of ALL <class period> a week
    ST72Q01 AS class_size,  -- Class Size - No of Students in <Test Language> Class
    IC05Q01 AS internet_at_sch,  -- Internet at School
    ST77Q01 AS mteacher_shows_interest,  -- Math Teaching - Teacher shows interest
    ST77Q02 AS mteacher_extra_help,  -- Math Teaching - Extra help
    ST77Q04 AS mteacher_helps,  -- Math Teaching - Teacher helps
    ST77Q05 AS mteacher_continues,  -- Math Teaching - Teacher continues
    ST77Q06 AS mteacher_express_opinion,  -- Math Teaching - Express opinions
    ST79Q05 AS teacher_give_feedback,  -- Formative Assessment - Gives Feedback
    ST79Q06 AS teacher_check_understanding,  -- Teacher-Directed Instruction - Checks Understanding
    ST79Q08 AS teacher_summ_prev_lesson,  -- Teacher-Directed Instruction - Summarizes Previous Lessons
    ST79Q11 AS teacher_give_feedback,  -- Formative Assessment - Gives Feedback on Strengths and Weaknesses
    ST79Q12 AS teacher_inform_expect,  -- Formative Assessment - Informs about Expectations
    ST79Q15 AS teacher_inform_learning_goals,  -- Teacher-Directed Instruction - Informs about Learning Goals
    ST79Q17 AS teacher_howto_get_better,  -- Formative Assessment - Tells How to Get Better
    ST80Q01 AS teacher_encourage_reflect_prob,  -- Cognitive Activation - Teacher Encourages to Reflect Problems
    ST80Q04 AS teacher_give_prob_think,  -- Cognitive Activation - Gives Problems that Require to Think
    ST83Q02 AS teacher_extra_help,  -- Teacher Support - Provides Extra Help When Needed
    ST83Q03 AS teacher_help_student_learn,  -- Teacher Support - Helps Students with Learning
    ST86Q01 AS get_along_teachers,  -- Student-Teacher Relation - Get Along with Teachers
    ST86Q02 AS teacher_interested,  -- Student-Teacher Relation - Teachers Are Interested
    ST86Q03 AS teacher_listen_student,  -- Student-Teacher Relation - Teachers Listen to Students
    ST86Q05 AS teacher_treat_student_fair,  -- Student-Teacher Relation - Teachers Treat Students Fair
       SCMAT AS math_self_concept,		-- Mathematics Self-Concept
       MATWKETH AS math_work_ethic,    -- Mathematics work ethic
	ANCMATWKETH AS math_work_ethic_anchored, 	-- Mathematics Work Ethic (Anchored)
	ANCMTSUP AS math_teacher_support_anchored,	--Mathematics Teacher Support (Anchored)
	ANCSCMAT AS math_self_concept_anchored, 	--Mathematics Self-Concept (Anchored)
    PV1MATH AS math_literacy_score,  -- Plausible value 1 in mathematics
    SENWGT_STU AS senate_weight, -- Senate weight - sum of weight within the country is 1000
	CAST(PV1MATH as DECIMAL(10,4)) * CAST(SENWGT_STU AS DECIMAL(10,4)) AS math_literacy_score_wt
from pisa
where CNT in ( 'China-Shanghai','Singapore','United States of America' )

### Read new pisa2012_data file into data frame

In [4]:
df_pisa = pd.read_csv('./data/pisa2012_data.csv')
df_pisa.head()

,country,sub_nation_code,stratum,OECD,natnl_center,school_id,mother_curr_job_status,father_curr_job_status,parents_believe_math_study,parents_believe_math_career,...,teacher_listen_student,teacher_treat_student_fair,math_self_concept,math_work_ethic,math_work_ethic_anchored,math_teacher_support_anchored,math_self_concept_anchored,math_literacy_score,senate_weight,math_literacy_score_wt
0,China-Shanghai,1560000,QCN0003,Non-OECD,China (Shanghai),1,"Other (e.g. home duties, retired)","Not working, but looking for a job",Agree,Strongly agree,...,Agree,Strongly agree,0.65,2.0389,2.4243,1.9408,1.0014,661.4815,0.1897,125.483041
1,China-Shanghai,1560000,QCN0003,Non-OECD,China (Shanghai),1,"Other (e.g. home duties, retired)",Working full-time <for pay>,Agree,Agree,...,Strongly agree,Strongly agree,0.88,2.7167,1.1311,0.5831,0.7562,676.4371,0.1897,128.320118
2,China-Shanghai,1560000,QCN0003,Non-OECD,China (Shanghai),1,Working full-time <for pay>,Working full-time <for pay>,NaN,NaN,...,Strongly agree,Strongly agree,-0.52,NaN,NaN,1.5224,0.2649,639.0481,0.1897,121.227425
3,China-Shanghai,1560000,QCN0003,Non-OECD,China (Shanghai),1,Working full-time <for pay>,Working full-time <for pay>,NaN,NaN,...,Strongly agree,Strongly agree,-0.76,NaN,NaN,0.4052,0.2052,740.9332,0.1897,140.555028
4,China-Shanghai,1560000,QCN0003,Non-OECD,China (Shanghai),1,"Other (e.g. home duties, retired)","Other (e.g. home duties, retired)",Strongly agree,Agree,...,NaN,NaN,NaN,2.0389,NaN,NaN,NaN,735.1690,0.1897,139.461559

### Prepare CSV file for Data Visualization phase
This next query was used to select a subset of categorical and quantitative variables to be used in this project.  The output of this query will be used to produce a new CSV file for the data visualization phase.

In [5]:
df_pisa_new = pd.DataFrame(df_pisa, columns=['country','gender','mother_curr_job_status',
'father_curr_job_status','parents_believe_math_career','parents_believe_math_study','parents_like_math','highest_parent_education_yrs',
'behaviour_max_math_sci_classes','behaviour_math_sci_college_major','behaviour_pursue_mathsci_career',
'math_interested', 'belonging_feel_lonely_sch', 'belonging_feel_happy_sch', 'belonging_feel_outsider', 'belonging_satisfied_atsch',
'familiar_arith_mean','familiar_complex_numb','familiar_congruent_fig','familiar_cosine','familiar_divisor','familiar_exp_function',
'familiar_linear_eq','familiar_polygon','familiar_probability','familiar_quadratic',
'familiar_radicals','familiar_rational_numb','familiar_vectors','mteacher_shows_interest',  
'mteacher_extra_help','mteacher_helps','mteacher_continues','mteacher_express_opinion',
'outof_school_study_time','outof_school_study_guided_hw','outof_school_study_tutor',
'outof_school_study_parent', 'no_of_math_classes_wk', 'no_of_all_classes_wk', 'class_size',
'math_self_concept', 'math_work_ethic', 'math_work_ethic_anchored', 'math_teacher_support_anchored', 'math_self_concept_anchored',    
'math_literacy_score','senate_weight'])

df_pisa_new.head()

,country,gender,mother_curr_job_status,father_curr_job_status,parents_believe_math_career,parents_believe_math_study,parents_like_math,highest_parent_education_yrs,behaviour_max_math_sci_classes,behaviour_math_sci_college_major,...,no_of_math_classes_wk,no_of_all_classes_wk,class_size,math_self_concept,math_work_ethic,math_work_ethic_anchored,math_teacher_support_anchored,math_self_concept_anchored,math_literacy_score,senate_weight
0,China-Shanghai,Male,"Other (e.g. home duties, retired)","Not working, but looking for a job",Strongly agree,Agree,Agree,12.0,Maximum classes Math,Major in college Math,...,NaN,NaN,NaN,0.65,2.0389,2.4243,1.9408,1.0014,661.4815,0.1897
1,China-Shanghai,Male,"Other (e.g. home duties, retired)",Working full-time <for pay>,Agree,Agree,Agree,16.0,Maximum classes Math,Major in college Math,...,NaN,NaN,NaN,0.88,2.7167,1.1311,0.5831,0.7562,676.4371,0.1897
2,China-Shanghai,Female,Working full-time <for pay>,Working full-time <for pay>,NaN,NaN,NaN,12.0,NaN,NaN,...,5.0,43.0,37.0,-0.52,NaN,NaN,1.5224,0.2649,639.0481,0.1897
3,China-Shanghai,Female,Working full-time <for pay>,Working full-time <for pay>,NaN,NaN,NaN,15.0,NaN,NaN,...,5.0,NaN,42.0,-0.76,NaN,NaN,0.4052,0.2052,740.9332,0.1897
4,China-Shanghai,Male,"Other (e.g. home duties, retired)","Other (e.g. home duties, retired)",Agree,Strongly agree,Agree,9.0,Maximum classes Math,Major in college Math,...,6.0,51.0,43.0,NaN,2.0389,NaN,NaN,NaN,735.1690,0.1897

In [6]:
df_pisa_new.info(max_cols=125)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15701 entries, 0 to 15700
Data columns (total 48 columns):
country                             15701 non-null object
gender                              15701 non-null object
mother_curr_job_status              15476 non-null object
father_curr_job_status              15102 non-null object
parents_believe_math_career         10363 non-null object
parents_believe_math_study          10374 non-null object
parents_like_math                   10355 non-null object
highest_parent_education_yrs        15536 non-null float64
behaviour_max_math_sci_classes      10190 non-null object
behaviour_math_sci_college_major    10179 non-null object
behaviour_pursue_mathsci_career     10143 non-null object
math_interested                     10361 non-null object
belonging_feel_lonely_sch           10307 non-null object
belonging_feel_happy_sch            10304 non-null object
belonging_feel_outsider             10321 non-null object
belonging_satisfied_atsch           10306 non-null object
familiar_arith_mean                 10263 non-null object
familiar_complex_numb               10279 non-null object
familiar_congruent_fig              10291 non-null object
familiar_cosine                     10281 non-null object
familiar_divisor                    10283 non-null object
familiar_exp_function               10303 non-null object
familiar_linear_eq                  10281 non-null object
familiar_polygon                    10276 non-null object
familiar_probability                10301 non-null object
familiar_quadratic                  10284 non-null object
familiar_radicals                   10278 non-null object
familiar_rational_numb              10284 non-null object
familiar_vectors                    10276 non-null object
mteacher_shows_interest             10388 non-null object
mteacher_extra_help                 10377 non-null object
mteacher_helps                      10367 non-null object
mteacher_continues                  10377 non-null object
mteacher_express_opinion            10381 non-null object
outof_school_study_time             9912 non-null float64
outof_school_study_guided_hw        9735 non-null float64
outof_school_study_tutor            10229 non-null float64
outof_school_study_parent           10225 non-null float64
no_of_math_classes_wk               10163 non-null float64
no_of_all_classes_wk                9159 non-null float64
class_size                          10097 non-null float64
math_self_concept                   10376 non-null float64
math_work_ethic                     10349 non-null float64
math_work_ethic_anchored            5135 non-null float64
math_teacher_support_anchored       10289 non-null float64
math_self_concept_anchored          10260 non-null float64
math_literacy_score                 15701 non-null float64
senate_weight                       15701 non-null float64
dtypes: float64(15), object(33)
memory usage: 5.7+ MB

In [7]:
df_pisa_new.to_csv('./data/pisa2012_data_clean.csv', index=False)